import { StyleSheet } from 'react-native';
import { Colors } from '../../styles/theme'


export const PopInStyles = StyleSheet.create({
    Background : {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0)', 
    },
    DeleteProject : {
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        top: '50%',
        left: '50%',
        transform: [{ translateX: -150 }, { translateY: -100 }],
        width:'80%',
        padding:30,
        gap:40,
        borderRadius: 20,
        backgroundColor: Colors.Background_Elements,
        borderWidth:1,
        borderColor:Colors.Button,
    },
    DeleteLabels: {
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        top: '50%',
        left: '50%',
        transform: [{ translateX: -150 }, { translateY: -100 }],
        width:'80%',
        padding:30,
        gap:40,
        borderRadius: 20,
        backgroundColor: Colors.Background_Primary,
        borderWidth:1,
        borderColor:Colors.Background_Elements,
    },
    NewProject : {
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        width:'80%',
        padding:20,
        gap:40,
        borderRadius: 20,
        backgroundColor: Colors.Background_Elements,
        borderWidth:1,
        borderColor:Colors.Button,
    },
    BackgroundBottom: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 9999, // important
    },
    SuccessPopup: {
        width: '100%',
        height: 300,
        backgroundColor: Colors.Background_Primary,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 15,
    },

    ExtractTextContainer: {
        width: '100%',
        padding: 13,
        backgroundColor: Colors.Background_Elements,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
});
